### _**TEXT GENERATOR :- NEXT WORD PREDICTOR**_

_FOR THE TRAINING PURPOSE WE HAVE TAKEN AN ARTICLE OF WHAT IS DECISION MAKING? ANF WE WILL FIRST TRAIN THE MODEL AND THEN PREDICT OUR NEXT WORD FROM IT._

In [5]:
faqs = ''' What is Decision Making?
Lets define decision making. Decision making is just what it sounds like: the action or process of making decisions. Sometimes we make logical decisions  but there are many times when we make emotional,irrational, and confusing choices. This page covers why we make poor decisions and discusses useful frameworks to expand your decision-making toolbox.

Why We Make Poor Decisions
I like to think of myself as a rational person, but I am not one. The good news is it is not just me or you. We are all irrational. For a long time, researchers and economists believed that humans made logical, well-considered decisions. In recent decades, however, researchers have uncovered a wide range of mental errors that derail our thinking. The articles below outline where we often go wrong and what to do about it.

5 Common Mental Errors That Sway You From Making Good Decisions: Lets talk about the mental errors that show up most frequently in our lives and break them down in easy-to-understand language. This article outlines how survivorship bias, loss aversion, the availability heuristic, anchoring, and confirmation bias sway you from making good decisions.
How to Spot a Common Mental Error That Leads to Misguided Thinking:
 Hundreds of psychology studies have proven that we tend to overestimate the importance of events we can easily recall and underestimate the importance of events we have trouble recalling. Psychologists refer to this little brain mistake as an illusory correlation.In this article, we talk about a simple strategy you can use to spot your hidden assumptions and prevent yourself from making an illusory correlation.
Two Harvard Professors Reveal One Reason Our Brains Love to Procrastinate: We have a tendency to care too much about our present selves and not enough about our future selves. If you want to beat procrastination and make better long-term choices, then you have to find a way to make your present self act in the best interest of your future self. This article breaks down three simple ways to do just that.
How to Use Mental Models for Smart Decision Making
The smartest way to improve your decision making skills is to learn mental models. A mental model is a framework or theory that helps to explain why the world works the way it does. Each mental model is a concept that helps us make sense of the world and offers a way of looking at the problems of life.

You can learn more about mental models, read how Nobel Prize-winning physicist Richard Feynman uses mental models, or browse a few of the most important mental models below.

Top Mental Models to Improve Your Decision Making

Margin of Safety: Always Leave Room for the Unexpected
How to Solve Difficult Problems by Using the Inversion Technique
Elon Musk and Bill Thurston on the Power of Thinking for Yourself
Best Decision Making Books
Thinking, Fast and Slow by Daniel Kahneman
Poor Charlies Almanack by Charles T. Munger
Seeking Wisdom by Peter Bevelin
Decisive by Chip Heath and Dan Heath '''

In [ ]:
#for converting text to numbers we will import tokeniser

In [6]:
#importing tensorflow libraries
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [7]:
tokenizer = Tokenizer() #make a tokeniser object

In [8]:
tokenizer.fit_on_texts([faqs])#to save our model in tokeniser

In [9]:
tokenizer.word_index #for checking the no. given to ur text

{'to': 1,
 'the': 2,
 'and': 3,
 'of': 4,
 'making': 5,
 'a': 6,
 'mental': 7,
 'we': 8,
 'that': 9,
 'decision': 10,
 'is': 11,
 'decisions': 12,
 'make': 13,
 'you': 14,
 'your': 15,
 'about': 16,
 'models': 17,
 'this': 18,
 'in': 19,
 'have': 20,
 'our': 21,
 'how': 22,
 'by': 23,
 'it': 24,
 'or': 25,
 'for': 26,
 'thinking': 27,
 'way': 28,
 'what': 29,
 'just': 30,
 'why': 31,
 'poor': 32,
 'not': 33,
 'good': 34,
 'errors': 35,
 'from': 36,
 'article': 37,
 'can': 38,
 'lets': 39,
 'like': 40,
 'logical': 41,
 'but': 42,
 'are': 43,
 'irrational': 44,
 'choices': 45,
 'i': 46,
 'as': 47,
 'one': 48,
 'long': 49,
 'researchers': 50,
 'below': 51,
 'do': 52,
 'common': 53,
 'sway': 54,
 'talk': 55,
 'most': 56,
 'down': 57,
 'bias': 58,
 'spot': 59,
 'importance': 60,
 'events': 61,
 'an': 62,
 'illusory': 63,
 'correlation': 64,
 'simple': 65,
 'use': 66,
 'yourself': 67,
 'present': 68,
 'selves': 69,
 'future': 70,
 'self': 71,
 'best': 72,
 'improve': 73,
 'learn': 74,
 'mode

In [10]:
len(tokenizer.word_index)#checking our article length

255

In [11]:
for sentence in faqs.split('\n'):
  print(sentence)

 What is Decision Making?
Lets define decision making. Decision making is just what it sounds like: the action or process of making decisions. Sometimes we make logical decisions  but there are many times when we make emotional irrational, and confusing choices. This page covers why we make poor decisions and discusses useful frameworks to expand your decision-making toolbox.

Why We Make Poor Decisions
I like to think of myself as a rational person, but I am not one. The good news is it is not just me or you. We are all irrational. For a long time, researchers and economists believed that humans made logical, well-considered decisions. In recent decades, however, researchers have uncovered a wide range of mental errors that derail our thinking. The articles below outline where we often go wrong and what to do about it.

5 Common Mental Errors That Sway You From Making Good Decisions: Lets talk about the mental errors that show up most frequently in our lives and break them down in eas

In [16]:
for sentence in faqs.split('\n'):
  print(tokenizer.texts_to_sequences([sentence])[0]) # as double list is created so to avoid that we used[0]

[29, 11, 10, 5]
[39, 80, 10, 5, 10, 5, 11, 30, 29, 24, 81, 40, 2, 82, 25, 83, 4, 5, 12, 84, 8, 13, 41, 12, 42, 85, 43, 86, 87, 88, 8, 13, 89, 44, 3, 90, 45, 18, 91, 92, 31, 8, 13, 32, 12, 3, 93, 94, 95, 1, 96, 15, 10, 5, 97]
[]
[31, 8, 13, 32, 12]
[46, 40, 1, 98, 4, 99, 47, 6, 100, 101, 42, 46, 102, 33, 48, 2, 34, 103, 11, 24, 11, 33, 30, 104, 25, 14, 8, 43, 105, 44, 26, 6, 49, 106, 50, 3, 107, 108, 9, 109, 110, 41, 111, 112, 12, 19, 113, 114, 115, 50, 20, 116, 6, 117, 118, 4, 7, 35, 9, 119, 21, 27, 2, 120, 51, 121, 122, 8, 123, 124, 125, 3, 29, 1, 52, 16, 24]
[]
[126, 53, 7, 35, 9, 54, 14, 36, 5, 34, 12, 39, 55, 16, 2, 7, 35, 9, 127, 128, 56, 129, 19, 21, 130, 3, 131, 132, 57, 19, 133, 1, 134, 135, 18, 37, 136, 22, 137, 58, 138, 139, 2, 140, 141, 142, 3, 143, 58, 54, 14, 36, 5, 34, 12]
[22, 1, 59, 6, 53, 7, 144, 9, 145, 1, 146, 27]
[147, 4, 148, 149, 20, 150, 9, 8, 151, 1, 152, 2, 60, 4, 61, 8, 38, 153, 154, 3, 155, 2, 60, 4, 61, 8, 20, 156, 157, 158, 159, 1, 18, 160, 161, 162, 47, 62

In [17]:
#we will check out as it is correct or not taking our first one i.e.[[29,11,10,5]] and then checking these values in tokeniser so the word coming out from this is what decision making is

In [18]:
input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [19]:
input_sequences

[[29, 11],
 [29, 11, 10],
 [29, 11, 10, 5],
 [39, 80],
 [39, 80, 10],
 [39, 80, 10, 5],
 [39, 80, 10, 5, 10],
 [39, 80, 10, 5, 10, 5],
 [39, 80, 10, 5, 10, 5, 11],
 [39, 80, 10, 5, 10, 5, 11, 30],
 [39, 80, 10, 5, 10, 5, 11, 30, 29],
 [39, 80, 10, 5, 10, 5, 11, 30, 29, 24],
 [39, 80, 10, 5, 10, 5, 11, 30, 29, 24, 81],
 [39, 80, 10, 5, 10, 5, 11, 30, 29, 24, 81, 40],
 [39, 80, 10, 5, 10, 5, 11, 30, 29, 24, 81, 40, 2],
 [39, 80, 10, 5, 10, 5, 11, 30, 29, 24, 81, 40, 2, 82],
 [39, 80, 10, 5, 10, 5, 11, 30, 29, 24, 81, 40, 2, 82, 25],
 [39, 80, 10, 5, 10, 5, 11, 30, 29, 24, 81, 40, 2, 82, 25, 83],
 [39, 80, 10, 5, 10, 5, 11, 30, 29, 24, 81, 40, 2, 82, 25, 83, 4],
 [39, 80, 10, 5, 10, 5, 11, 30, 29, 24, 81, 40, 2, 82, 25, 83, 4, 5],
 [39, 80, 10, 5, 10, 5, 11, 30, 29, 24, 81, 40, 2, 82, 25, 83, 4, 5, 12],
 [39, 80, 10, 5, 10, 5, 11, 30, 29, 24, 81, 40, 2, 82, 25, 83, 4, 5, 12, 84],
 [39,
  80,
  10,
  5,
  10,
  5,
  11,
  30,
  29,
  24,
  81,
  40,
  2,
  82,
  25,
  83,
  4,
  5,
  12,
 

In [20]:
[len(x) for x in input_sequences]

[2,
 3,
 4,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 2,
 3,
 4,
 5,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 

In [21]:
max_len = max([len(x) for x in input_sequences])

In [23]:
#zero padding
from tensorflow.keras.preprocessing.sequence import pad_sequences
pad_sequences(input_sequences, maxlen = max_len, padding='pre')

array([[  0,   0,   0, ...,   0,  29,  11],
       [  0,   0,   0, ...,  29,  11,  10],
       [  0,   0,   0, ...,  11,  10,   5],
       ...,
       [  0,   0,   0, ..., 254,  79,   3],
       [  0,   0,   0, ...,  79,   3, 255],
       [  0,   0,   0, ...,   3, 255,  79]], dtype=int32)

In [24]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')#storing in a variable

In [25]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  29,  11],
       [  0,   0,   0, ...,  29,  11,  10],
       [  0,   0,   0, ...,  11,  10,   5],
       ...,
       [  0,   0,   0, ..., 254,  79,   3],
       [  0,   0,   0, ...,  79,   3, 255],
       [  0,   0,   0, ...,   3, 255,  79]], dtype=int32)

In [26]:
padded_input_sequences[:,:-1]#for input

array([[  0,   0,   0, ...,   0,   0,  29],
       [  0,   0,   0, ...,   0,  29,  11],
       [  0,   0,   0, ...,  29,  11,  10],
       ...,
       [  0,   0,   0, ...,  23, 254,  79],
       [  0,   0,   0, ..., 254,  79,   3],
       [  0,   0,   0, ...,  79,   3, 255]], dtype=int32)

In [27]:
X = padded_input_sequences[:,:-1]

In [28]:
padded_input_sequences[:,-1]#for output

array([ 11,  10,   5,  80,  10,   5,  10,   5,  11,  30,  29,  24,  81,
        40,   2,  82,  25,  83,   4,   5,  12,  84,   8,  13,  41,  12,
        42,  85,  43,  86,  87,  88,   8,  13,  89,  44,   3,  90,  45,
        18,  91,  92,  31,   8,  13,  32,  12,   3,  93,  94,  95,   1,
        96,  15,  10,   5,  97,   8,  13,  32,  12,  40,   1,  98,   4,
        99,  47,   6, 100, 101,  42,  46, 102,  33,  48,   2,  34, 103,
        11,  24,  11,  33,  30, 104,  25,  14,   8,  43, 105,  44,  26,
         6,  49, 106,  50,   3, 107, 108,   9, 109, 110,  41, 111, 112,
        12,  19, 113, 114, 115,  50,  20, 116,   6, 117, 118,   4,   7,
        35,   9, 119,  21,  27,   2, 120,  51, 121, 122,   8, 123, 124,
       125,   3,  29,   1,  52,  16,  24,  53,   7,  35,   9,  54,  14,
        36,   5,  34,  12,  39,  55,  16,   2,   7,  35,   9, 127, 128,
        56, 129,  19,  21, 130,   3, 131, 132,  57,  19, 133,   1, 134,
       135,  18,  37, 136,  22, 137,  58, 138, 139,   2, 140, 14

In [29]:
y = padded_input_sequences[:,-1]

In [30]:
X.shape

(493, 76)

In [31]:
y.shape

(493,)

In [ ]:
#as a classification task:-Binary or multiclass we use multiclass classification and in that we will do one hot encoding for transforming

In [32]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=256)

In [33]:
y.shape

(493, 256)

In [34]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [35]:
#embedding layer:- dence vector for every word for better representation after that lstm and after that for output as for softmax we will use dense layer

In [36]:
#importing necessary libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [46]:
model = Sequential()
model.add(Embedding(256, 100, input_length=76))
model.add(LSTM(150))
model.add(Dense(256, activation='softmax'))

In [47]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [48]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 76, 100)           25600     
                                                                 
 lstm_2 (LSTM)               (None, 150)               150600    
                                                                 
 dense_2 (Dense)             (None, 256)               38656     
                                                                 
Total params: 214856 (839.28 KB)
Trainable params: 214856 (839.28 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [49]:
X

array([[  0,   0,   0, ...,   0,   0,  29],
       [  0,   0,   0, ...,   0,  29,  11],
       [  0,   0,   0, ...,  29,  11,  10],
       ...,
       [  0,   0,   0, ...,  23, 254,  79],
       [  0,   0,   0, ..., 254,  79,   3],
       [  0,   0,   0, ...,  79,   3, 255]], dtype=int32)

In [50]:
model.fit(X,y,epochs=100)

Epoch 1/100
16/16 [==============================] - 4s 117ms/step - loss: 5.5362 - accuracy: 0.0101
Epoch 2/100
16/16 [==============================] - 2s 111ms/step - loss: 5.3511 - accuracy: 0.0284
Epoch 3/100
16/16 [==============================] - 2s 127ms/step - loss: 5.1469 - accuracy: 0.0426
Epoch 4/100
16/16 [==============================] - 3s 181ms/step - loss: 5.1016 - accuracy: 0.0426
Epoch 5/100
16/16 [==============================] - 2s 112ms/step - loss: 5.0862 - accuracy: 0.0446
Epoch 6/100
16/16 [==============================] - 2s 111ms/step - loss: 5.0660 - accuracy: 0.0426
Epoch 7/100
16/16 [==============================] - 2s 113ms/step - loss: 5.0280 - accuracy: 0.0426
Epoch 8/100
16/16 [==============================] - 2s 114ms/step - loss: 4.9660 - accuracy: 0.0568
Epoch 9/100
16/16 [==============================] - 2s 114ms/step - loss: 4.8792 - accuracy: 0.0568
Epoch 10/100
16/16 [==============================] - 3s 203ms/step - loss: 4.7555 - accura

In [51]:
text = "Improve"
#Tokenisation
token_text = tokenizer.texts_to_sequences([text])[0]
#padding
padded_token_text = pad_sequences([token_text],maxlen=76,padding='pre')
print(padded_token_text)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0 73]]


In [52]:
text = "Improve"
#Tokenisation
token_text = tokenizer.texts_to_sequences([text])[0]
#padding
padded_token_text = pad_sequences([token_text],maxlen=76,padding='pre')
#predict
model.predict(padded_token_text)

1/1 [==============================] - 0s 421ms/step


array([[6.08347079e-07, 8.08854997e-02, 2.35219675e-04, 2.16547446e-03,
        4.01128903e-02, 1.42331263e-02, 1.33464963e-03, 1.02780171e-01,
        4.23423294e-03, 8.83812172e-05, 4.47656214e-02, 1.32627547e-01,
        5.13537030e-04, 7.09672924e-04, 1.33255972e-02, 3.55284631e-01,
        2.60548637e-04, 3.61535395e-03, 1.24890284e-04, 3.41491909e-06,
        4.20698925e-04, 9.47122026e-05, 1.68758797e-05, 1.02260220e-03,
        1.20498221e-02, 7.77426583e-04, 4.26402927e-04, 2.03187628e-05,
        1.30608026e-02, 5.09129968e-05, 4.23152640e-04, 1.32478177e-04,
        9.32058506e-03, 1.81613184e-04, 1.99045862e-05, 1.00293988e-03,
        9.55572395e-05, 4.63802188e-08, 3.12390737e-03, 1.68374663e-06,
        4.38327342e-02, 9.29120215e-05, 3.85218882e-05, 3.12231205e-05,
        3.37408483e-06, 2.89907093e-05, 1.32439254e-06, 8.16564891e-04,
        6.68181656e-06, 1.92790922e-05, 1.31497309e-05, 3.37732054e-04,
        1.14634349e-04, 7.12387636e-03, 3.23698296e-05, 1.476801

In [53]:
model.predict(padded_token_text).shape

1/1 [==============================] - 0s 29ms/step


(1, 256)

In [54]:
#for checking the highest probablity of the word we have to import numpy
import numpy as np

In [55]:
np.argmax(model.predict(padded_token_text))

1/1 [==============================] - 0s 26ms/step


15

In [56]:
tokenizer.word_index

{'to': 1,
 'the': 2,
 'and': 3,
 'of': 4,
 'making': 5,
 'a': 6,
 'mental': 7,
 'we': 8,
 'that': 9,
 'decision': 10,
 'is': 11,
 'decisions': 12,
 'make': 13,
 'you': 14,
 'your': 15,
 'about': 16,
 'models': 17,
 'this': 18,
 'in': 19,
 'have': 20,
 'our': 21,
 'how': 22,
 'by': 23,
 'it': 24,
 'or': 25,
 'for': 26,
 'thinking': 27,
 'way': 28,
 'what': 29,
 'just': 30,
 'why': 31,
 'poor': 32,
 'not': 33,
 'good': 34,
 'errors': 35,
 'from': 36,
 'article': 37,
 'can': 38,
 'lets': 39,
 'like': 40,
 'logical': 41,
 'but': 42,
 'are': 43,
 'irrational': 44,
 'choices': 45,
 'i': 46,
 'as': 47,
 'one': 48,
 'long': 49,
 'researchers': 50,
 'below': 51,
 'do': 52,
 'common': 53,
 'sway': 54,
 'talk': 55,
 'most': 56,
 'down': 57,
 'bias': 58,
 'spot': 59,
 'importance': 60,
 'events': 61,
 'an': 62,
 'illusory': 63,
 'correlation': 64,
 'simple': 65,
 'use': 66,
 'yourself': 67,
 'present': 68,
 'selves': 69,
 'future': 70,
 'self': 71,
 'best': 72,
 'improve': 73,
 'learn': 74,
 'mode

In [58]:
pos =np.argmax(model.predict(padded_token_text))

1/1 [==============================] - 0s 30ms/step


In [60]:
for word,index in tokenizer.word_index.items():
    if index == pos:
      print(word)


your


In [ ]:
#so it is predicing correct word after it.

_**